name: Fetch Repository Stats
concurrency: fetch-repository-stats

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run-ghrs-with-matrix:
    name: repostats-for-nice-projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repositories to generate reports for.
        statsRepo: [
            3ds-varitech/
            ai-whois-parser/
            aliyun-scripts/
            ansible-scripts/
            asm-8085/
            asm-editor/
            astro-aside/
            astro-downloadchecklist/
            astro-downloadtable/
            astro-seo/
            astro-tocbutton/
            astro-ytembed/
            classic-checkpassword/
            cloudflare-scripts/
            cs-automata-theory/
            cs-prenex/
            eBBS/
            fastfetch-themes/
            fc-certbot/
            fc-exchange-rate-update/
            fc-gomail/
            fc-webpage-screenshot/
            geonames-loader/
            gettext-extractor/
            gettext-po2json/
            gettext-spellchecker/
            gettext-translator/
            git-scripts/
            go-bash-env-redact/
            go-config/
            go-database/
            gofiber-ip-middleware/
            gofiber-recaptcha3-middleware/
            gofiber-recovery-middleware/
            gofiber-roles-middleware/
            gofiber-validator-middleware/
            gofiber-zitadel-middleware/
            go-playground-recaptcha3-validator/
            go-playground-uts-validator/
            gormcache/
            gorm-model-generator/
            go-slugify/
            go-storage/
            intldate/
            jabberd2-auth-linux.patch/
            lambda-html-tidy/
            letsencrypt-scripts/
            music-drums/
            music-keyboard/
            mysql-encrypted-backup/
            nagios-check-domain/
            nagios-check-domain-ai/
            nagios-check-ping-go/
            nagios-check-ssl-expiration/
            ndjbdns-scripts/
            php5-ext-crack2/
            python-gpt-po/
            rgglez/
            rgglez-cs-thesis-scip/
            rgglez-website/
            rust-checkpassword/
            shiki-pddl/
            smelte/
            Spreadsheet_Excel_Writer/
            ssl-validator/
            storage/
            svelte-alerts/
            svelte-frappe-charts/
            svelte-i18n/
            svelte-i18n-gettext/
            svelte-mediaquery/
            svelte-notoriuosbutton/
            svelte-quill/
            svelte-seo/
            webkit2png-daemon/
            whois-parser-ai/
            yii-emailsintaxvalidator/
            yii-emailsmtpvalidator/
            yii-emailvalidator/
            yii-ftpassetmanager/
            yii-htmlpurifier/
            yii-jui/
            yii-svelte-simpleautocomplete/
            yii-webfeed/]
      # Do not cancel&fail all remaining jobs upon first job failure.
      fail-fast: false
      # Help avoid commit conflicts. Note(JP): this should not be
      # necessary anymore, feedback appreciated
      max-parallel: 1
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.ghrs_github_api_token }}
